# Generated by Django 3.2 on 2025-03-28 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluator', '0005_alter_question_programming_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='duration_in_minutes',
            field=models.IntegerField(default=0),
        ),
    ]
